apiVersion: v1
kind: Service
metadata:
  name: library-api-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: libraryproducer
    name: libraryproducer
  type: NodePort