apiVersion: v1
kind: Service
metadata:
  name: libraryproducer
  labels:
    app: libraryproducer
    tier: backend
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8080
  selector:
    app: libraryproducer
    tier: backend